name: Main Workflow
on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build Action
        uses: ./.github/actions/build
        with:
          run_number: ${{ github.run_number }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Test Action
        uses: ./.github/actions/test
        with:
          run_number: ${{ github.run_number }}
