name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build Workflow
        uses: ./.github/workflows/build.yml
        with:
          run_number: ${{ github.run_number }}

      - name: Run Test Workflow
        uses: ./.github/workflows/test.yml
        with:
          run_number: ${{ github.run_number }}
