name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      run_number: ${{ github.run_number }}
    secrets: inherit

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      run_number: ${{ github.run_number }}
    secrets: inherit
