name: Main Workflow

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      run_number: ${{ github.run_number }}

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      run_number: ${{ github.run_number }}
