# .github/workflows/test.yml
name: Test

on:
  workflow_call:
    inputs:
      run_number:
        required: true
        type: number

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ github.run_id }}
          path: test-reports/*.xml
          if-no-files-found: ignore
